/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Star.gltf -o src/components/Star.jsx -r public
Star by Kay Lousberg (https://market.pmnd.rs/model/star)
*/

import { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

const Star = (props) => {
  const { nodes, materials } = useGLTF("/models/Star.gltf");
  const ref = useRef();

  useFrame(() => {
    // Rotate the star around its Y-axis
    ref.current.rotation.y += 0.01;
  });
  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh
        geometry={nodes.star.geometry}
        material={materials["Yellow.030"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
};

useGLTF.preload("/models/Star.gltf");

export default Star;
